### ISSUE TITLE
CSS docs

### ISSUE THREAD

**Issue by hirasso** [swup/a11y-plugin#19]
**Describe the problem**

Intuitively, I would have thought that this CSS should hide any outline on the `<main>` element:

```css
main:focus {
  outline: none;
}
```

But in the docs it recommends this approach:

```css
main[tabindex="-1"] {
  outline: none;
}
```
In my tests, it works well with the simple `:focus` selector. Is there a reason for the `[tabindex]` form being chosen in the docs?
