### ISSUE TITLE
Disable animations if user prefers reduced motion

### ISSUE THREAD

**Issue by daun** [swup/a11y-plugin#6]
Evaluate whether we should disable transitions for devices that request reduced motion:

- **Pro**: Conceptually, it's well within this plugin's core idea
- **Con**: Technically, this belongs in CSS
- **Con**: Turning off animations isn't reducing but removing motion completely
- Probably make this an optional feature turned off by default

**Details**

[Revisiting the reduced motion media query](https://css-tricks.com/revisiting-prefers-reduced-motion-the-reduced-motion-media-query/)

**Example code**

```css
@media screen and
  (prefers-reduced-motion: reduce), 
  (update: slow) {
  .transition-fade {
    transition-duration: 0.001ms !important;
  }
}
```
